GET http://localhost:5049/games

###
GET http://localhost:5049/games/2

###
POST http://localhost:5049/games
Content-Type: application/json

{
    "name": "Dragon Ball Fighter",
    "genreId": "2",
    "price": 10,
    "releaseDate": "2009-05-28"
}

###
PUT http://localhost:5049/games/5
Content-Type: application/json

{
    "name": "Metin 2",
    "genre": "MMORPG",
    "price": 20,
    "releaseDate": "2010-11-25"
}

###
DELETE http://localhost:5049/games/2
